version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/var/lib/mongodb
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
