apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nestjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nestjs-app
  template:
    metadata:
      labels:
        app: my-nestjs-app
    spec:
      containers:
        - name: my-nestjs-app
          image: DOCKER_USERNAME/my-nestjs-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/prod-db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
