version: '3.9'
services:
  oni-leaves-app-server:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    image: oni-leaves-app-server
    container_name: oni-leaves-app-server
    restart: always
    ports:
      - 8990:5001
    env_file:
      - ./../.prod.env
    # environment:
    #   - MONGO_URL_DB=mongodb://mongodb:27017/leaves-db
    # volumes:
    #   - .:/app
    depends_on:
      - mongodb
    networks:
      - leaves-network

  mongodb:
    image: mongo:6.0-focal
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=onidb
      - MONGO_INITDB_ROOT_PASSWORD=oni1234
    ports:
      - '27017:27017'
    # volumes:
    #   - ./initdb.d:/docker-entrypoint-initdb.d
    volumes:
      - dbdata6:/data/mongodb
    networks:
      - leaves-network


  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=onidb
      - ME_CONFIG_MONGODB_ADMINPASSWORD=oni1234
      - ME_CONFIG_MONGODB_URL=mongodb://onidb:oni1234@mongodb:27017
    ports:
      - '8082:8081'
    networks:
      - leaves-network
    depends_on:
      - mongodb
    

volumes:
  dbdata6:

networks:
  leaves-network:
    driver: bridge
